### ISSUE TITLE
Failing to build

### ISSUE THREAD

**Issue by JeroenoBoy** [tujoworker/gatsby-plugin-wrap-pages#2]
i'm getting the following error when trying to build
![yes](https://user-images.githubusercontent.com/26047623/130500993-cfcee2cd-96d7-4a15-b7d8-851010ff5968.png)
the path to that file is "src/pages/dashboard/[id]/layout.tsx"

**Comment by tujoworker** [comment]
Hi again @JeroenoBoy!

I can't reproduce your issue. Maybe you can provide me with some more details? What OS, Node.js and Gatsby version etc.
I added [an example](https://github.com/tujoworker/gatsby-plugin-wrap-pages/tree/main/example-layout) of how I think your setup is.

Do you have added this to your `gatsby-config.js` file?:

```js
{
    resolve: 'gatsby-plugin-wrap-pages',
    options: { wrapperName: 'layout.tsx' },
  }
```

**Comment by JeroenoBoy** [comment]
Thanks for taking your time about looking into this issue,

The version's im using are:
- gatsby: 3.12.0
- gatsby-plugin-wrap-pages: 1.0.4
- react: 17.0.2
- react-dom: 17.0.2

And for your question, that is what i added to `gatbsy-config.js`.

i'm not sure if its of any use but here is my `layout.tsx`
```ts
//  using any and logging since im not sure what this returns
export function layout(data: any) {
	console.log(data);
	return (
		<DashboardGuildLayout params={{ id: '' }} uri={''}>
			{data.element}
		</DashboardGuildLayout>
	)
}
```

**Comment by JeroenoBoy** [comment]
Maybe i've found part of the issue,
.cache/wpe-scopes.js uses \ instead of /, the result is:
```js
export * as _55e10b1f8ba15d472d4b631319d10cc6 from '../src\pages\dashboard\[id]\layout.tsx';
```

**Comment by JeroenoBoy** [comment]
I got it to work for now in a bit of a "Hacky way", i created this file:
![image](https://user-images.githubusercontent.com/26047623/130613491-dc519957-ed8e-4f2e-99ad-0daef69d0b58.png)

**Comment by tujoworker** [comment]
Thank you for all the details! 

The reason is [this line](https://github.com/tujoworker/gatsby-plugin-wrap-pages/blob/696583a6217875476b88f41aa9bde1104f227c4a/gatsby-plugin-wrap-pages/plugin-logic.js#L188) where I use `systemPath.sep` – I may change that to an ordinary slash. Not sure why Node.js gives us a backslash 🤦‍♂️

**Comment by tujoworker** [comment]
v1.0.6 should fix this. Can you run `gatsby clean` and try this version? Hope it works! And let me know how it went. 

PS: Yes, you need to have named exports as you mentioned: `wrapPages` or `wrapPagesDeep`

**Comment by JeroenoBoy** [comment]
No, I'm still having the same errors. I have concluded that the issue is coming from [this line](https://github.com/tujoworker/gatsby-plugin-wrap-pages/blob/75f7f862b8e57c420f1f9495662ceef5f788e038/gatsby-plugin-wrap-pages/plugin-logic.js#L172). I will create a PR soon that fixed the issue.
